// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARlOcQ2lIfBuLK_UjbYX91PdJjK-0gc_E',
    appId: '1:890972034116:web:bf3dbf7f0360d010fa9811',
    messagingSenderId: '890972034116',
    projectId: 'kytypablo-7bcf6',
    authDomain: 'kytypablo-7bcf6.firebaseapp.com',
    storageBucket: 'kytypablo-7bcf6.appspot.com',
    measurementId: 'G-YJY99K4CJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQse9Dkf3lBofy8Go80nf4T8MXjvPUqak',
    appId: '1:890972034116:android:beda65a543c422a8fa9811',
    messagingSenderId: '890972034116',
    projectId: 'kytypablo-7bcf6',
    storageBucket: 'kytypablo-7bcf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDURM2ROx32x9Fqvw9hvKbQroXdH9gBZk',
    appId: '1:890972034116:ios:ce2fed6d4aaa33c4fa9811',
    messagingSenderId: '890972034116',
    projectId: 'kytypablo-7bcf6',
    storageBucket: 'kytypablo-7bcf6.appspot.com',
    iosBundleId: 'rfvi.pablobeltran.kytypablo',
  );
}
